// One entry per admin-editable content domain.
//
// ContentManager.jsx renders entirely from these, so adding a domain is a schema
// plus an endpoint — not another screen. The FAQ endpoint predates the generic
// /api/content/[type] handler and wraps its payload differently, which is what
// listKey/itemKey exist to absorb.

export const CONTENT_SCHEMAS = [
  {
    key: "faqs",
    label: "FAQs",
    singular: "FAQ",
    endpoint: "/api/admin/faqs",
    listKey: "faqs",
    itemKey: "faq",
    primary: "question",
    secondary: "answer",
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
    ],
  },
  {
    key: "projects",
    label: "Projects",
    singular: "Project",
    endpoint: "/api/content?type=projects",
    listKey: "items",
    itemKey: "item",
    primary: "title",
    secondary: "description",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image_url", label: "Image or video", type: "media", folder: "projects" },
      {
        name: "icon_name",
        label: "Icon name (used when there is no image)",
        type: "text",
        hint: "Bot, Box, Brain, Camera, Clapperboard, Code2, Gamepad2, GraduationCap, Music, Palette, Presentation, Trophy, Users. Leave blank or misspell it and the category's own icon is used.",
      },
      { name: "is_real", label: 'Show the "Real" badge', type: "checkbox" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "news",
    label: "News",
    singular: "News item",
    endpoint: "/api/content?type=news",
    listKey: "items",
    itemKey: "item",
    primary: "title",
    secondary: "description",
    fields: [
      { name: "tag", label: "Tag", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "image_url",
        label: "Image or video",
        type: "media",
        folder: "news",
        hint: "Upload from your computer, or paste a path such as /news/photo.jpg.",
      },
      { name: "is_real", label: 'Show the "Real" badge', type: "checkbox" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "staff",
    label: "Staff",
    singular: "Lecturer",
    endpoint: "/api/content?type=staff",
    listKey: "items",
    itemKey: "item",
    primary: "name",
    secondary: "specialty",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "title", label: "Academic title", type: "text", hint: "Assoc. Prof., Asst. Prof., Prof., or Lecturer." },
      { name: "specialty", label: "Specialty", type: "textarea" },
      { name: "education", label: "Education", type: "textarea" },
      { name: "photo_url", label: "Photo", type: "media", folder: "staff" },
      {
        name: "profile_url",
        label: "Profile URL",
        type: "text",
        hint: "Leave blank and the card links to the department directory instead.",
      },
      { name: "room", label: "Room", type: "text" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "student_types",
    label: "Student types",
    singular: "Student type",
    endpoint: "/api/content?type=student_types",
    listKey: "items",
    itemKey: "item",
    primary: "label",
    secondary: "id",
    fields: [
      {
        name: "id",
        label: "Key",
        type: "text",
        required: true,
        hint: "Lowercase, no spaces — fee rows reference this. Cannot be changed after creation.",
      },
      { name: "label", label: "Display label", type: "text", required: true },
      { name: "semester_fee", label: "Tuition per semester (THB)", type: "number", min: 0 },
      { name: "has_living_cost", label: "Show estimated living costs", type: "checkbox" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "fee_rows",
    label: "Fee rows",
    singular: "Fee row",
    endpoint: "/api/content?type=fee_rows",
    listKey: "items",
    itemKey: "item",
    primary: "item",
    secondary: "student_type_id",
    fields: [
      {
        name: "student_type_id",
        label: "Student type key",
        type: "text",
        required: true,
        hint: "Must match a key from the Student types tab.",
      },
      {
        name: "period",
        label: "Period",
        type: "select",
        required: true,
        options: ["Per Semester", "Full 4 Years"],
      },
      { name: "item", label: "Item", type: "text", required: true },
      {
        name: "item_type",
        label: "Item type",
        type: "select",
        required: true,
        options: ["Mandatory", "One-time", "Optional"],
      },
      { name: "amount", label: "Amount (THB)", type: "number", min: 0 },
      {
        name: "excluded_from_total",
        label: "Exclude from the per-semester total",
        type: "checkbox",
      },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "courses",
    label: "Courses",
    singular: "Course",
    endpoint: "/api/content?type=courses",
    listKey: "items",
    itemKey: "item",
    // site_courses is keyed by course code, not a generated uuid.
    idField: "code",
    primary: "name",
    secondary: "code",
    fields: [
      {
        name: "code",
        label: "Course code",
        type: "text",
        required: true,
        hint: "e.g. EN 843 402. Cannot be changed after creation.",
      },
      { name: "name", label: "Course name", type: "text", required: true },
      { name: "credits", label: "Credits", type: "text", hint: "e.g. 3(3-0-6)" },
      { name: "description_en", label: "Description (English)", type: "textarea" },
      { name: "description_th", label: "Description (Thai)", type: "textarea" },
      { name: "prerequisites", label: "Prerequisites", type: "text" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "study_plan",
    label: "Study plan",
    singular: "Study plan row",
    endpoint: "/api/content?type=study_plan",
    listKey: "items",
    itemKey: "item",
    primary: "course_name",
    secondary: "course_code",
    fields: [
      { name: "year", label: "Year", type: "number", required: true, min: 0, hint: "1 to 4." },
      {
        name: "semester_name",
        label: "Semester",
        type: "select",
        required: true,
        options: ["Semester 1", "Semester 2", "Summer"],
      },
      {
        name: "total_accumulated",
        label: "Accumulated credits by end of semester",
        type: "number",
        min: 0,
        hint: "Leave blank for Summer.",
      },
      {
        name: "course_code",
        label: "Course code",
        type: "text",
        required: true,
        hint: "A real code, or a placeholder like EN XX XXXX for a free choice slot.",
      },
      { name: "course_name", label: "Course name", type: "text", required: true },
      { name: "credits", label: "Credits", type: "text" },
      {
        name: "course_type",
        label: "Course type",
        type: "select",
        required: true,
        options: ["Gen Ed", "Fundamental", "Compulsory", "Elective", "Practical Training", "Free Elective"],
      },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "elective_courses",
    label: "Elective tracks",
    singular: "Elective course",
    endpoint: "/api/content?type=elective_courses",
    listKey: "items",
    itemKey: "item",
    primary: "course_name",
    secondary: "track",
    fields: [
      {
        name: "track",
        label: "Track",
        type: "select",
        required: true,
        options: ["AI", "Digital Media", "Interactive", "Software"],
      },
      { name: "course_code", label: "Course code", type: "text", required: true },
      { name: "course_name", label: "Course name", type: "text", required: true },
      { name: "credits", label: "Credits", type: "text" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "chat_misses",
    label: "Unanswered",
    singular: "Unanswered question",
    endpoint: "/api/content?type=chat_misses",
    listKey: "items",
    itemKey: "item",
    primary: "question",
    secondary: "asked_at",
    // Written by the chatbot, never by hand. The list is the content backlog:
    // read it, add an FAQ that answers the question, then dismiss the entry.
    readOnly: true,
    fields: [],
  },
];

export function emptyValues(schema) {
  return schema.fields.reduce((acc, f) => {
    acc[f.name] = f.type === "checkbox" ? false : f.type === "number" ? 0 : "";
    return acc;
  }, {});
}
